# Generated by Django 2.0 on 2018-12-24 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='管理员名称')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='邮箱')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='机构名称')),
                ('parent_id', models.BigIntegerField(default=-1, verbose_name='父机构ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='租户名称')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='租户电话')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='租户邮箱')),
                ('status', models.IntegerField(blank=True, choices=[(1, '可用'), (2, '冻结')], default=1, verbose_name='租户状态')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.Tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='manager',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.Tenant', verbose_name='租户'),
        ),
    ]
