# Generated by Django 2.0.2 on 2018-10-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='管理员名称')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=500, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='机构名称')),
                ('parent_id', models.BigIntegerField(default=-1, verbose_name='父机构ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='租户名称')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='租户电话')),
                ('email', models.CharField(blank=True, max_length=500, verbose_name='租户邮箱')),
                ('status', models.SmallIntegerField(blank=True, verbose_name='租户状态')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.Tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='manager',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.Tenant', verbose_name='租户'),
        ),
    ]
