# Generated by Django 2.0 on 2018-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '可用'), (2, '冻结')], verbose_name='租户状态'),
        ),
    ]
