# Generated by Django 2.0.2 on 2018-08-27 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180827_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(verbose_name='关门时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='identify',
            field=models.CharField(default=uuid.UUID('6cfb73ec-164a-43b5-a2a8-e8331510468e'), help_text='门店标识号', max_length=30, verbose_name='门店标识号'),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(verbose_name='开始营业时间'),
        ),
    ]
