# Generated by Django 2.0.2 on 2018-08-27 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180827_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='brief_introduce',
            field=models.TextField(max_length=500, null=True, verbose_name='门店简介'),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='关门时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='identify',
            field=models.CharField(default=uuid.UUID('a4e60b4c-1d53-48c8-9ee4-2b150d704649'), help_text='门店标识号', max_length=30, verbose_name='门店标识号'),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='开始营业时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='门店评分'),
        ),
    ]
