# Generated by Django 2.0.2 on 2018-08-27 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180827_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, default='Mon Aug 27 11:49:57 2018', null=True, verbose_name='关门时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='identify',
            field=models.CharField(default=uuid.UUID('886313e1-3b8a-5372-9b90-0c9aee199e5d'), help_text='门店标识号', max_length=30, verbose_name='门店标识号'),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, default='Mon Aug 27 11:49:57 2018', null=True, verbose_name='开始营业时间'),
        ),
    ]
