# Generated by Django 2.0.2 on 2018-08-27 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180827_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 53, 11, 730286), null=True, verbose_name='关门时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 53, 11, 730286), null=True, verbose_name='开始营业时间'),
        ),
    ]
