# Generated by Django 2.0.2 on 2018-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20180827_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='关门时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='开始营业时间'),
        ),
    ]
