# Generated by Django 2.0 on 2018-12-24 14:24

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('province', models.CharField(default='beijing', max_length=100, verbose_name='省份')),
                ('city', models.CharField(default='beijing', max_length=100, verbose_name='城市')),
                ('district', models.CharField(default='dongcheng', max_length=100, verbose_name='区域')),
                ('address_detail', models.CharField(default='详细地址', max_length=100, verbose_name='详细地址')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('address_type', models.IntegerField(choices=[(1, '管理员地址'), (2, '用户住址'), (3, '用户收货地址'), (4, '门店地址')], help_text='1-管理员地址，2-用户住址，3-用户收货地址,4-门店地址', verbose_name='地址类型')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
    ]
