# Generated by Django 2.0.2 on 2018-08-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('common', '0002_auto_20180824_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresses',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address',
            new_name='address_detail',
        ),
    ]
