# Generated by Django 2.0 on 2018-12-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_multilanguage_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multilanguage',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
