# Generated by Django 2.0 on 2018-12-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_multi_language_picture_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multi_Language',
        ),
        migrations.DeleteModel(
            name='Picture_Resource',
        ),
    ]
