# Generated by Django 2.0 on 2018-12-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_multilanguage_pictureresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multilanguage',
        ),
        migrations.DeleteModel(
            name='PictureResource',
        ),
    ]
