# Generated by Django 2.0 on 2018-12-24 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('size', models.IntegerField(null=True, verbose_name='文件大小')),
                ('resource_url', models.CharField(default='', max_length=4096, verbose_name='文件路径')),
                ('original_name', models.TextField(default='', max_length=100, verbose_name='原文件名')),
                ('name', models.TextField(default='', max_length=100, verbose_name='文件名')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
            ],
            options={
                'verbose_name': '文件资源',
                'verbose_name_plural': '文件资源',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('information_type', models.IntegerField(blank=True, choices=[(0, '新闻'), (1, '图片'), (2, '文档')], default=1, verbose_name='图文类型')),
                ('information_status', models.IntegerField(blank=True, choices=[(0, '待审核'), (1, '审核中'), (2, '审核通过'), (3, '审核不通过'), (4, '已发布')], default=0, verbose_name='图文状态')),
                ('audit_reason', models.CharField(blank=True, max_length=2048, null=True, verbose_name='审核原因')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.Tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '图文',
                'verbose_name_plural': '图文',
            },
        ),
        migrations.CreateModel(
            name='MultilanguageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='多语言名称')),
                ('language_code', models.CharField(blank=True, default='chi', max_length=50, verbose_name='语言编码')),
                ('description', models.TextField(max_length=4096, null=True, verbose_name='描述')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_language_informations', to='information.Information', verbose_name='图文')),
            ],
            options={
                'verbose_name': '图文多语言',
                'verbose_name_plural': '图文多语言',
            },
        ),
        migrations.CreateModel(
            name='PosterResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('creator', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('modify', models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者')),
                ('transaction_id', models.BigIntegerField(default=1, verbose_name='事务ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('size', models.IntegerField(null=True, verbose_name='文件大小')),
                ('resource_url', models.CharField(default='', max_length=4096, verbose_name='文件路径')),
                ('original_name', models.TextField(default='', max_length=100, verbose_name='原文件名')),
                ('name', models.TextField(default='', max_length=100, verbose_name='文件名')),
                ('horizontal_resoution', models.IntegerField(null=True, verbose_name='垂直分辨率')),
                ('vertical_resoution', models.IntegerField(null=True, verbose_name='水平分辨率')),
                ('delete_flag', models.BooleanField(default=True, verbose_name='有效标识')),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster_resources', to='information.Information', verbose_name='图文')),
            ],
            options={
                'verbose_name': '图片资源',
                'verbose_name_plural': '图片资源',
            },
        ),
        migrations.AddField(
            model_name='fileresource',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_resources', to='information.Information', verbose_name='图文'),
        ),
    ]
