# Generated by Django 2.0 on 2018-11-27 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='creator',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='delete_flag',
            field=models.BooleanField(default=True, verbose_name='有效标识'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='modify',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='transaction_id',
            field=models.BigIntegerField(default=1, verbose_name='事务ID'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='information',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='information',
            name='creator',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='information',
            name='delete_flag',
            field=models.BooleanField(default=True, verbose_name='有效标识'),
        ),
        migrations.AddField(
            model_name='information',
            name='modify',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='information',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='information',
            name='transaction_id',
            field=models.BigIntegerField(default=1, verbose_name='事务ID'),
        ),
        migrations.AddField(
            model_name='information',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='creator',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='delete_flag',
            field=models.BooleanField(default=True, verbose_name='有效标识'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='modify',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='transaction_id',
            field=models.BigIntegerField(default=1, verbose_name='事务ID'),
        ),
        migrations.AddField(
            model_name='multilanguageinformation',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='creator',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='delete_flag',
            field=models.BooleanField(default=True, verbose_name='有效标识'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='modify',
            field=models.CharField(default=users.models.UserProfile, max_length=100, verbose_name='修改者'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='transaction_id',
            field=models.BigIntegerField(default=1, verbose_name='事务ID'),
        ),
        migrations.AddField(
            model_name='posterresource',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Information', verbose_name='图文'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='name',
            field=models.TextField(default='', max_length=100, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='original_name',
            field=models.TextField(default='', max_length=100, verbose_name='原文件名'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='resource_url',
            field=models.CharField(default='', max_length=4096, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='information',
            name='audit_reason',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='审核原因'),
        ),
        migrations.AlterField(
            model_name='information',
            name='information_status',
            field=models.IntegerField(blank=True, choices=[(0, '待审核'), (1, '审核中'), (2, '审核通过'), (3, '审核不通过'), (4, '已发布')], default=0, verbose_name='图文状态'),
        ),
        migrations.AlterField(
            model_name='information',
            name='information_type',
            field=models.IntegerField(blank=True, choices=[(0, '新闻'), (1, '图片'), (2, '文档')], default=1, verbose_name='图文类型'),
        ),
        migrations.AlterField(
            model_name='multilanguageinformation',
            name='description',
            field=models.TextField(max_length=4096, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='multilanguageinformation',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Information', verbose_name='图文'),
        ),
        migrations.AlterField(
            model_name='multilanguageinformation',
            name='language_code',
            field=models.CharField(blank=True, default='chi', max_length=50, verbose_name='语言编码'),
        ),
        migrations.AlterField(
            model_name='posterresource',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Information', verbose_name='图文'),
        ),
        migrations.AlterField(
            model_name='posterresource',
            name='name',
            field=models.TextField(default='', max_length=100, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='posterresource',
            name='original_name',
            field=models.TextField(default='', max_length=100, verbose_name='原文件名'),
        ),
        migrations.AlterField(
            model_name='posterresource',
            name='resource_url',
            field=models.CharField(default='', max_length=4096, verbose_name='文件路径'),
        ),
    ]
