# Generated by Django 2.0 on 2018-12-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lems', '0001_initial'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInformationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.ManyToManyField(to='lems.Category')),
            ],
            options={
                'verbose_name': '图文和目录的关联关系',
                'verbose_name_plural': '图文和目录的关联关系',
            },
        ),
    ]
