# Generated by Django 2.0 on 2018-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lems', '0001_initial'),
        ('information', '0002_categoryinformationrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryinformationrelation',
            name='categorys',
        ),
        migrations.AddField(
            model_name='information',
            name='categorys',
            field=models.ManyToManyField(to='lems.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryInformationRelation',
        ),
    ]
